<?php

//MENU
define("AZIENDA","AZIENDA");
define("PROFILO","PROFILO");
define("PROFILO_AZIENZA","Profilo");
define("CERTIFICAZIONI","CERTIFICAZIONI");
define("CERTIFICAZIONI_AZIENDA","Cerificazioni");
define("AMBIENTE","AMBIENTE");
define("AMBIENTE_AZIENDA","Ambiente");
define("CONSULENZA","CONSULENZA");
define("CONSULENZA_AZIENDA","Consulenza");
define("VIDEO","VIDEO");
define("VIDEO_AZIENDA","Video");
define("PRESS","PRESS");
define("PRESS_AZIENDA","Press");
define("DESIGN","DESIGN");
define("DESIGN_AZIENDA","Design");
define("SHOWROOM","SHOWROOM");
define("PRODOTTI","PRODOTTI");
define("WORKING","WORKING SYSTEM");
define("EXECUTIVE","EXECUTIVE COLLECTION");
define("RECEPTION","RECEPTION");
define("STORAGE","STORAGE");
define("WALL","WALL");
define("CLASSICAL","CLASSICAL");
define("NEWS","NEWS");
define("REFERENZE","REFERENZE");
define("GALLERIA","GALLERIA PROGETTI");
define("CONTATTI","CONTATTI");
define("CONTATTATECI","CONTATTATECI");
define("DOVE_SIAMO","DOVE SIAMO");
define("LOGIN","LOGIN / REGISTRATI");
define("AREA","AREA RISERVATA");
define("SEGUICI","Seguici su:");
//LABELS
define("FINITURE_MISURE","Finiture e misure");
define("CATALOGO","Catalogo");
define("SELEZIONA_POSIZIONE","Seleziona posizione");
define("SELEZIONA_REGIONE","Seleziona Regione");
define("SELEZIONA_PROVINCIA","Provincia");
define("TESTO_LOGIN","L'area \"login/registrati\" di Prof consente in pochi istanti agli utenti interessati di scaricare i cataloghi di ogni prodotto.</br> Per effettuare l'accesso all'area download &egrave necessario compilare il form presente in questa pagina. Sar&agrave sufficiente inserire i propri dati una sola volta, e mai durante gli accessi successivi. Registrandosi si fornisce il consenso a ricevere newsletter di Prof, che potranno essere revocate in qualsiasi momento utilizzando il tasto \"UNSUBSCRIBE\" presente in ciascuna newsletter. L'utilizzo dei testi e delle immagini scaricate da questo sito &egrave permesso a condizione che venga menzionata Prof.");
define("TESTO_LOGIN_AREARISERVATA","Inserisci la tua login e password per entrare nell'area riservata.");
define("ERRORE_LOGIN","Login o password errata.");
define("REGISTRAZIONE_OK","La ringraziamo per essersi registrato. Prima di effettuare il login dovr&agrave; confermare il suo indirizzo di posta cliccando sul link di attivazione che ha ricevuto tramite mail.");
define("REGISTRAZIONE_KO","Ci sono dei problemi in fase di registrazione degli utenti, la preghiamo di riprovare pi&ugrave; tardi.");
define("LOGIN_AREARISERVATA","LOGIN:");
define("ESEGUI_LOGIN","LOGIN");
define("PASSWORD:","PASSWORD:");
define("BTN_LOGIN","Entra");
define("ESITO_LOGIN","Login o password errata. Riprova.");
define("REGISTRATI","REGISTRATI");
define("TESTO_REGISTRATI","Registrati compilando il seguente form:");
define("NOME","Nome:");
define("COGNOME","Cognome:");
define("EMAIL","Email:");
define("TELEFONO","Telefono:");
define("PROVINCIA","Provincia:");
define("REGIONE","Regione:");
define("NAZIONE","Nazione:");
define("INDIRIZZO","Indirizzo:");
define("POSIZIONE","Posizione:");
define("CODICE_SICUREZZA","Codice sicurezza:");
define("AZIENDA_FORM","Azienda");
define("ARCHITETTO","Architetto");
define("INGEGNERE","Ingegnere");
define("RAPPRESENTANTE","Rappresentante");
define("RIVENDITORE","Rivenditore");
define("PRIVATO","Privato");
define("ALTRO","Altro");
define("TESTO","Testo:");
define("PASSWORD_REGISTRAZIONE","Password:");
define("CONFERMA_PASSWORD","Conferma password:");
define("PRIVACY","Autorizzo Profoffice S.r.l. al trattamento dei miei dati personali, ai sensi della legge 675 del 1996.");
define("MATERIALE","Autorizzo Profoffice S.r.l. all'invio di materiale pubblicitario ed informativo.");
define("INVIA","Invia");
define("OK","Grazie esserti resgistrato. Ora puoi scaricare il catalogo allegato ai prodotti.");
define("ERRORE","Al momento non &egrave; possibile inviare messaggi.<br/>Ti preghiamo di riprovare pi&ugrave; tardi.");
define("DATI_OBBLIGATORI","* Campo obbligatorio");
define("ACCOUNT_NON_ATTIVATO","L'account non &egrave; attivo. Per attivare l'account consulta la mail che hai ricevuto al momento della registrazione.");
define("COMPILA_FORM_SENDMAIL","Per informazioni invia una mail a");
define("COMPILA_FORM_FILLFORM","Oppure compila il seguente form");
define("COMPILA_FORM_REQUIRED","Tutti i campi sono obbligatori.");
define("LOGIN_AREA","Login:");
define("LOGIN_AREA_TITOLO","LOGIN");
define("PASSWORD_AREA","Password:");
define("LOGIN_OK","Utente autenticato. Ora pu&ograve; consulatre il catalogo allegato ai modelli a catagolo.");
define("SPEDIZIONE_OK","Grazie per averci contattato. Le risponderemo al pi&ugrave; presto.");
define("SPEDIZIONE_KO","Al momento non &egrave; possibile inviare messaggi. La preghiamo di riprovare pi&ugrave; tardi.");
define("PASSWORD_DIMENTICATA","Password dimenticata (?)");
define("EMAIL_CORRETTA","Una mail con i dati di accesso sono stati inviati all'inidirizzo inserito.");
define("EMAIL_ERRATA","La mail inserita non risulta registrata.<br>Ti preghiamo di controllarla e riprovare.");
define("INDICAZIONI_STRADALI","Indicazioni stradali");
define("DESC_AREA_RISERVATA","L'area \"area riservata\" di Prof consente ad architetti, giornalisti e utenti interessati di scaricare le immagini a bassa e ad alta risoluzione, disegni 3D, documenti tecnici (schede prodotto, istruzioni di montaggio e di manutenzione) e altro. Per effettuare l'accesso all'area \"area riservata\" &egrave necessario richiedere una password utente direttamente all'ufficio commerciale di Prof dopo aver inserito i propri dati nel'area \"login/registrati\". Sar&agrave sufficiente inserire i propri dati una sola volta, e mai durante gli accessi successivi. L'utilizzo dei testi e delle immagini scaricate da questo sito  permesso a condizione che venga menzionata Prof.");
define("REFERENZE_TESTO","SELEZIONA UN CONTINENTE PER VEDERE LE NOSTRE REFERENZE:");
define("REFERENZE_EUROPA","EUROPA");
define("REFERENZE_ASIA","ASIA");
define("REFERENZE_AMERICA","AMERICA");
define("REFERENZE_AFRICA","AFRICA");
define("REFERENZE_OCEANIA","OCEANIA");
define("CERTIFICAZIONE_TESTO", "A conferma del suo impegno per la qualità, Prof S.rl. è certificata UNI EN ISO 9001:2008 e rispetta le normative internazionali per la qualità nella progettazione, nello sviluppo, nella fabbricazione e nell’assistenza ai clienti. L'indroduzione della certificazione permette a Prof S.r.l. di rispondere in modo adeguato alle esigenze normative di settore e di mercato.<br /><br />Prof S.r.l ha sempre posto, inoltre, una particolare attenzione all'ambiente introducendo un sistema certificato UNI EN ISO 14001:2004 che lo attesta!<br /><br />Scarica le nostre certificazioni:");
define("AMBIENTE_TESTO", "In un mondo costantemente alla ricerca della qualità, ma sempre più sensibile alle problematiche ecologiche, Prof mette in campo la massima professionalità nella progettazione e realizzazione dei mobili. Allo stesso temp non trascura l’ambiente che ci circonda.<br /><br />Dalla materia prima accuratamente selezionata, all’intero processo di trasformazione e imballaggio fino allo smaltimento, tutto è finalizzato alla salvaguardia della salute ed al risparmio energetico.<br /><br />Il rispetto delle norme in materia ambientale, il sistematico monitoraggio delle fasi produttive, ma, in particolare, l’innata tendenza di Prof alla correttezza, al rispetto del lavoro e del mercato, le hanno permesso di ottenere la certificazione ISO14001.");
define("CONSULENZA_TESTO", "Già vincente nel design giovane e minimalista, Prof fa sua l’idea di “chiavi in mano” dando vita ad un connubio cliente-fornitore. Iniziando dalla presa visione degli spazi, accompagna il committente nella realizzazione del progetto fino al suo concretizzarsi in un ambiente di lavoro pratico e confortevole.<br />Dalla scelta della disposizione, passando per la svariata gamma di colori e finiture, mai dimenticando quanto siano importanti le esigenze e gusti personali del cliente.<br />Un agile reparto commerciale ed un altrettanto organizzato e coordinato settore progettazione permettono di raggiungere risultati di eccellenza.");
define("DESIGN_TESTO", "Nel settore del mobile per ufficio vigono regole normative ben definite, dove l’ergonomia e la funzionalità regnano sovrane. Avvalendosi della collaborazione di giovani designer dalle idee innovative, designer che siano in grado di cogliere l’evoluzione delle tendenze, PROF dà forma alle idee coniugandole con praticità e rispetto delle norme.<br />La cura nel dettaglio e i materiali pregiati fungono da coronamento all’impegno di PROF nel realizzare splendidi oggetti di arredamento. Il prodotto finale, pur collocandosi in più fasce di mercato, non tradisce mai questa filosofia aziendale.");
?>