<?php

//MENU
define("AZIENDA","COMPANY");
define("PROFILO","PROFILE");
define("CERTIFICAZIONI","CERTIFICATIONS");
define("AMBIENTE","ENVIRONMENT");
define("CONSULENZA","ADVISING");
define("DESIGN","DESIGN");
define("SHOWROOM","SHOWROOM");
define("VIDEO","VIDEO");
define("PRODOTTI","PRODUCTS");
define("WORKING","WORKING SYSTEM");
define("EXECUTIVE","EXECUTIVE COLLECTION");
define("RECEPTION","RECEPTION");
define("STORAGE","STORAGE");
define("WALL","WALL");
define("CLASSICAL","CLASSICAL");
define("NEWS","NEWS");
define("REFERENZE","REFERENCES");
define("GALLERIA","PROJECTS GALLERY");
define("CONTATTI","CONTACTS");
define("CONTATTATECI","CONTACT US");
define("DOVE_SIAMO","WHERE WE ARE");
define("LOGIN","LOGIN/REGISTER");
define("AREA","RESERVED AREA");
define("SEGUICI","Follow us:");
//LABELS
define("FINITURE_MISURE","Details and measures");
define("CATALOGO","Catalogue");
define("SELEZIONA_POSIZIONE","Select rule");
define("SELEZIONA_REGIONE","Select region");
define("SELEZIONA_PROVINCIA","Select province");
define("ESEGUI_LOGIN","LOGIN");
define("TESTO_LOGIN","Prof download area allows users to download any catalogue product quickly. To log into the download area, you must fill in the form on this page. Just enter your personal data once, and never during any subsequent logins. By registering you consent to receiving the Prof newsletter. You may opt-out at any time by selecting the \"UNSUBSCRIBE\" button in each newsletter. The use of texts and images or their reproduction in printed form is permitted provided that  Prof is mentioned.");
define("TESTO_LOGIN_AREARISERVATA","Insert your login e password to enter reserved area.");
define("ERRORE_LOGIN","Login or password incorrect.");
define("REGISTRAZIONE_OK","Thank you to register. Before you can login you have to activate your account clicking the link in registration email you have received.");
define("REGISTRAZIONE_KO","There are some problmes with registration process. Try again later.");
define("LOGIN_AREARISERVATA","LOGIN:");
define("PASSWORD:","PASSWORD:");
define("BTN_LOGIN","Enter");
define("ESITO_LOGIN","Wrong login or password. Please try again.");
define("REGISTRATI","REGISTER");
define("TESTO_REGISTRATI","Register filing following form:");
define("NOME","Name:");
define("COGNOME","Surname:");
define("EMAIL","Email:");
define("TELEFONO","Phone:");
define("PROVINCIA","Province:");
define("REGIONE","Region:");
define("NAZIONE","Country:");
define("INDIRIZZO","Address:");
define("POSIZIONE","Position:");
define("CODICE_SICUREZZA","Security code:");
define("ARCHITETTO","Architect");
define("INGEGNERE","Engineer");
define("RAPPRESENTANTE","Agent");
define("RIVENDITORE","Dealer");
define("PRIVATO","Private");
define("ALTRO","Other");
define("TESTO","Text:");
define("PASSWORD_REGISTRAZIONE","Password:");
define("CONFERMA_PASSWORD","Retype password:");
define("PRIVACY","I authorize Profoffice S.r.l. to use my personal data in accordance with law 675 of 1996.");
define("MATERIALE","I authorize Profoffice S.r.l. to send advertising and informational materials.");
define("INVIA","Send");
define("OK","Thank you for register. Now you can download catalog attached to products.");
define("ERRORE","There is a temporary problem with our server. Plese try again later...");
define("DATI_OBBLIGATORI","* Required Field");
define("ACCOUNT_NON_ATTIVATO","Account is not active. To activate youy account plese check mail you have received after registration.");
define("COMPILA_FORM_SENDMAIL","To contact us, please send an e-mail using this e-mail address");
define("COMPILA_FORM_FILLFORM","Otherwise, filling in the following form");
define("COMPILA_FORM_REQUIRED","All fields are required");
define("LOGIN_AREA_TITOLO","LOGIN");
define("LOGIN_AREA","Login:");
define("PASSWORD_AREA","Password:");
define("LOGIN_OK","User logged in. Now you can access to the catalougue attached to all models.");
define("SPEDIZIONE_OK","Thank you for having contacted us. We will answer you as soon as possible.");
define("SPEDIZIONE_KO","There is a temporary problem with our server. Plese try again later...");
define("PASSWORD_DIMENTICATA","Forgotten password (?)");
define("EMAIL_CORRETTA","A email was sent to your email address with your password.");
define("EMAIL_ERRATA","This email does not exist. Please check it and try again.");
define("INDICAZIONI_STRADALI","Direction");
define("DESC_AREA_RISERVATA","Prof \"reserved area\" allows architects, journalists and users who want to download low and high resolution images, 3D drawings, technical documents (product data sheets, assembly and maintenance instructions) and so on. To log into the \"reserved area\", it is necessary to ask a user password directly to Prof commercial dept. after having registered the personal data in the \"login/register\" area. Just enter your personal data once, and never during any subsequent logins. The use of texts and images or their reproduction in printed form is permitted provided that Prof is mentioned.");
define("REFERENZE_TESTO","SELECT A CONTINENT TO SEE OUR REFERENCES:");
define("REFERENZE_EUROPA","EUROPE");
define("REFERENZE_ASIA","ASIA");
define("REFERENZE_AMERICA","AMERICA");
define("REFERENZE_AFRICA","AFRICA");
define("REFERENZE_OCEANIA","OCEANIA");
?>