<?php

//MENU
define("AZIENDA","AZIENDA");
define("PROFILO","PROFILO");
define("CERTIFICAZIONI","CERTIFICAZIONI");
define("AMBIENTE","AMBIENTE");
define("CONSULENZA","CONSULENZA");
define("DESIGN","DESIGN");
define("SHOWROOM","SHOWROOM");
define("VIDEO","VIDEO");
define("PRODOTTI","PRODOTTI");
define("WORKING","WORKING SYSTEM");
define("EXECUTIVE","EXECUTIVE COLLECTION");
define("RECEPTION","RECEPTION");
define("STORAGE","STORAGE");
define("WALL","WALL");
define("CLASSICAL","CLASSICAL");
define("NEWS","NEWS");
define("REFERENZE","REFERENZE");
define("GALLERIA","GALLERIA PROGETTI");
define("CONTATTI","CONTATTI");
define("CONTATTATECI","CONTATTATECI");
define("DOVE_SIAMO","DOVE SIAMO");
define("LOGIN","LOGIN/REGISTRATI");
define("AREA","AREA RISERVATA");
define("SEGUICI","Seguici su:");
//LABELS
define("FINITURE_MISURE","Finiture e misure");
define("CATALOGO","Catalogo");
define("SELEZIONA_POSIZIONE","Seleziona posizione");
define("SELEZIONA_REGIONE","Seleziona regione");
define("SELEZIONA_PROVINCIA","Seleziona provincia");
define("TESTO_LOGIN","L'area \"login/registrati\" di Prof consente in pochi istanti agli utenti interessati di scaricare i cataloghi di ogni prodotto.</br> Per effettuare l'accesso all'area download &egrave necessario compilare il form presente in questa pagina. Sar&agrave sufficiente inserire i propri dati una sola volta, e mai durante gli accessi successivi. Registrandosi si fornisce il consenso a ricevere newsletter di Prof, che potranno essere revocate in qualsiasi momento utilizzando il tasto \"UNSUBSCRIBE\" presente in ciascuna newsletter. L'utilizzo dei testi e delle immagini scaricate da questo sito &egrave permesso a condizione che venga menzionata Prof.");
define("TESTO_LOGIN_AREARISERVATA","Inserisci la tua login e password per entrare nell'area riservata.");
define("ERRORE_LOGIN","Login o password errata.");
define("REGISTRAZIONE_OK","La ringraziamo per essersi registrato. Prima di effettuare il login dovr&agrave; confermare il suo indirizzo di posta cliccando sul link di attivazione che ha ricevuto tramite mail.");
define("REGISTRAZIONE_KO","Ci sono dei problemi in fase di registrazione degli utenti, la preghiamo di riprovare pi&ugrave; tardi.");
define("LOGIN_AREARISERVATA","LOGIN:");
define("ESEGUI_LOGIN","LOGIN");
define("PASSWORD:","PASSWORD:");
define("BTN_LOGIN","Entra");
define("ESITO_LOGIN","Login o password errata. Riprova.");
define("REGISTRATI","REGISTRATI");
define("TESTO_REGISTRATI","Regsitrati compilando il seguente form:");
define("NOME","Nome*:");
define("COGNOME","Cognome*:");
define("EMAIL","Email*:");
define("TELEFONO","Telefono:");
define("PROVINCIA","Provincia:");
define("REGIONE","Regione:");
define("NAZIONE","Nazione*:");
define("INDIRIZZO","Indirizzo:");
define("POSIZIONE","Posizione*:");
define("CODICE_SICUREZZA","Codice sicurezza:");
define("ARCHITETTO","Architetto");
define("INGEGNERE","Ingegnere");
define("RAPPRESENTANTE","Rappresentante");
define("RIVENDITORE","Rivenditore");
define("PRIVATO","Privato");
define("ALTRO","Altro");
define("TESTO","Testo:");
define("PASSWORD_REGISTRAZIONE","Password*:");
define("CONFERMA_PASSWORD","Conferma password*:");
define("PRIVACY","Autorizzo Profoffice S.r.l. al trattamento dei miei dati personali, ai sensi della legge 675 del 1996.");
define("MATERIALE","Autorizzo Profoffice S.r.l. all'invio di materiale pubblicitario ed informativo.");
define("INVIA","Invia");
define("OK","Grazie esserti resgistrato. Ora puoi scaricare il catalogo allegato ai prodotti.");
define("ERRORE","Al momento non &egrave; possibile inviare messaggi. Ti preghiamo di riporovare pi&ugrave; tardi.");
define("DATI_OBBLIGATORI","* Campo obbligatorio");
define("ACCOUNT_NON_ATTIVATO","L'account non &egrave; attivo. Per attivare l'account consulta la mail che hai ricevuto al momento della registrazione.");
define("COMPILA_FORM","Per contattarci inviaci un'email utilizzando il link seguente, oppure compila il form qui di seguito.");
define("LOGIN_AREA","Login:*");
define("LOGIN_AREA_TITOLO","LOGIN");
define("PASSWORD_AREA","Password:*");
define("LOGIN_OK","Utente autenticato. Ora pu&ograve; consulatre il catalogo allegato ai modelli a catagolo.");
define("SPEDIZIONE_OK","Grazie per averci contattato. Le risponderemo al pi&ugrave; presto.");
define("SPEDIZIONE_KO","Al momento non &egrave; possibile inviare messaggi. La preghiamo di riporovare pi&ugrave; tardi.");
define("PASSWORD_DIMENTICATA","Password dimenticata (?)");
define("EMAIL_CORRETTA","Una mail con i dati di accesso sono stati inviati all'inidirizzo inserito.");
define("EMAIL_ERRATA","La mail inserita non risulta registrata.<br>Ti preghiamo di controllarla e riprovare.");
define("INDICAZIONI_STRADALI","Indicazioni stradali");
define("DESC_AREA_RISERVATA","L'area \"area riservata\" di Prof consente ad architetti, giornalisti e utenti interessati di scaricare le immagini a bassa e ad alta risoluzione, disegni 3D, documenti tecnici (schede prodotto, istruzioni di montaggio e di manutenzione) e altro. Per effettuare l'accesso all'area \"area riservata\" &egrave necessario richiedere una password utente direttamente all'ufficio commerciale di Prof dopo aver inserito i propri dati nel'area \"login/registrati\". Sar&agrave sufficiente inserire i propri dati una sola volta, e mai durante gli accessi successivi. L'utilizzo dei testi e delle immagini scaricate da questo sito  permesso a condizione che venga menzionata Prof.");
define("REFERENZE_TESTO","SELEZIONA UN CONTINENTE PER VEDERE LE NOSTRE REFERENZE:");
define("REFERENZE_EUROPA","EUROPA");
define("REFERENZE_ASIA","ASIA");
define("REFERENZE_AMERICA","AMERICA");
define("REFERENZE_AFRICA","AFRICA");
define("REFERENZE_OCEANIA","OCEANIA");
?>